version: '3.3'

services:


  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7 no Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always # Todas a atualizações deste arquivo, sempre serão atualizadas automaticamente no projeto do compose
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: yohrannes
      MYSQL_PASSWORD: secret

  wordpress:
    depends_on: # Determina quais serviços o wordpress depende, que deverão ser executados antes do serviço do wordpress...
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: yohrannes
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}